@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor SystemUser as Actor
participant ScheduleMeetingUI as UI
participant AuthzRegistry as AuthzRes
participant AuthorizationService as AuthzSvc
participant UserSession as UserS
participant ListUsersController as UsersController
participant ScheduleMeetingController as Controller
participant UserManagementService as Usersvc
participant MeetingRepository as Repo
participant InviteRepository as InviteRepo

-> UI: Schedule meeting
activate UI
    UI -> AuthzRes : authz=authorizationService()
    activate AuthzRes
    deactivate AuthzRes
    UI -> AuthzSvc : s=session()
    activate AuthzSvc
    deactivate AuthzSvc
    UI -> UserS : myUser=authenticatedUser()
    activate UserS
    deactivate UserS

    UI -> UsersController: create()
    activate UsersController
    deactivate UsersController
    UI -> Controller: create(authz, meetingRepository, InviteRepository)
    activate Controller
    deactivate Controller
    UI -> Controller: saveMeeting(meetingDuration, meetingDate, meetingTime)
    activate Controller
        Controller -> Repo : save(meetingDuration, meetingDate, meetingTime)
        activate Repo
        deactivate Repo
    deactivate Controller
    UI -> UsersController: allUsers()
    activate UsersController
        UsersController -> Usersvc : allUsers()
        activate Usersvc
        Usersvc --> UsersController : system users
        deactivate Usersvc
        UsersController --> UI : system users
    deactivate UsersController
    loop for each selected user
    UI --> Actor : shows system users

    Actor -> UI : selects User

    UI -> Controller : saveInvite(myUser, systemUser, meeting)
    activate Controller
        Controller -> InviteRepo : save(myUser, systemUser, meeting)
        activate InviteRepo
        deactivate InviteRepo
    deactivate Controller

    UI --> Actor : invite sent
    end

deactivate UI
@enduml